name: BHC Auto Merge Manifest PR

on:
  pull_request:
    types: [labeled]
    branches:
      - develop
  issues:
    types: [labeled]
    branches:
      - develop

jobs:
  call_auto_pr_workflow:
    uses: rdkcentral/build_tools_workflows/.github/workflows/bhc_auto_merge_manifest_pr.yml@develop
    secrets:
      rdke_github_token: ${{ secrets.RDKCM_RDKE }}
